name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2.3.4
    
    - name: Setup Java JDK
      uses: actions/setup-java@v2.2.0
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Releasing using Hub
      uses: actions/upload-artifact@v2.2.4
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
